### ISSUE TITLE
Test TrenchBoot support on AMD hardware with TPM 2.0 and TPM 1.2 with legacy boot mode

### ISSUE THREAD

**Issue by BeataZdunczyk** [TrenchBoot/trenchboot-issues#23]
**Is your feature request related to a problem? Please describe.**

After the implementation of the updated TrenchBoot boot protocol for AMD platforms in Secure Kernel Loader, it is necessary to test the solution on AMD hardware with TPM 2.0 and TPM 1.2 with legacy boot mode to ensure proper functionality.

**Is your feature request related to a new idea or technology that
would benefit the project? Please describe.**

This issue is required to ensure that the TrenchBoot support for AMD platforms with TPM 2.0 and TPM 1.2 with legacy boot mode works properly after the implementation of the updated TrenchBoot boot protocol for AMD platforms in Secure Kernel Loader.

**Describe the solution you'd like**

Test the TrenchBoot support on AMD hardware with TPM 2.0 and TPM 1.2 with legacy boot mode to ensure proper functionality after the implementation of the updated TrenchBoot boot protocol for AMD platforms in Secure Kernel Loader.

**Describe alternatives you've considered**

N/A

**Additional context**

This feature request is part of Phase 4 in TrenchBoot as Anti Evil Maid project, as outlined in the documentation: https://docs.dasharo.com/projects/trenchboot-aem-v2/.

**Relevant documentation you've consulted**

N/A

**Comment by miczyg1** [comment]
Proposed hardware:

- KGPE-D16 - legacy boot with TPM 1.2 and TPM 2.0 (two board available in 3dmeb lab, one with TPm 1.2 and the other one with TPM 2.0)
- Supermicro M11SDV-4C-LN4F - UEFI boot with TPM 2.0 (can also be swapped with a TPM 1.2 to test TPM 1.2 in UEFI mode, may also be used to test legacy boot mode with CSM)

**Comment by krystian-hebel** [comment]
>     * KGPE-D16 - legacy boot with TPM 1.2 and TPM 2.0 (two board available in 3dmeb lab, one with TPm 1.2 and the other one with TPM 2.0)

One doesn't work, the other works only [until HVM is started](https://github.com/QubesOS/qubes-issues/issues/9150#issuecomment-2075267133). Some limited testing was done by starting with `spec-ctrl=no-ibpb-entry` - this is not safe, but allowed to show that AEM works on multi-node system.

>     * Supermicro M11SDV-4C-LN4F - UEFI boot with TPM 2.0 (can also be swapped with a TPM 1.2 to test TPM 1.2 in UEFI mode, may also be used to test legacy boot mode with CSM)

Doesn't work, CPU can't send DRTM sequence to TPM properly.

Most of the tests were performed on HP t630 platforms, one with TPM 1.2 and the other with TPM 2.0. Other platforms were too problematic, be it because of bad firmware (vendor firmware on KGPE doesn't support TPM 2.0, and coreboot doesn't work reliably) or hardware issues (CPU on Supermicro, IBPB on KGPE, problems with KVM everywhere) not directly linked to AEM.

---

Proof of installation and execution with TPM 2.0:
![Screenshot_2024-04-11_10-14-40](https://github.com/TrenchBoot/trenchboot-issues/assets/40995177/d994cdd0-24f9-4cdb-90af-f00fe569bd85)
![Screenshot_2024-04-16_08-59-18](https://github.com/TrenchBoot/trenchboot-issues/assets/40995177/f408f32d-0475-42a2-a16b-8fbb5b71f47d)
![Screenshot_2024-04-16_08-59-43](https://github.com/TrenchBoot/trenchboot-issues/assets/40995177/ba54a64e-9f48-4598-b39c-8108b9f2d9b2)

Execution with TPM 1.2:

![Screenshot_2024-05-17](https://github.com/TrenchBoot/trenchboot-issues/assets/40995177/00a88dc4-2056-4fef-b4c0-f3ad2ff06c9d)
